export enum WeatherEffect {
  ashenvaleHeavyRain = FourCC("RAhr"),
  ashenvaleLightRain = FourCC("RAlr"),
  dalaranShield = FourCC("MEds"),
  dungeonHeavyBlueFog = FourCC("FDbh"),
  dungeonLightBlueFog = FourCC("FDbl"),
  dungeonHeavyGreenFog = FourCC("FDgh"),
  dungeonLightGreenFog = FourCC("FDgl"),
  dungeonHeavyRedFog = FourCC("FDrh"),
  dungeonLightRedFog = FourCC("FDrl"),
  dungeonHeavyWhiteFog = FourCC("FDwh"),
  dungeonLightWhiteFog = FourCC("FDwl"),
  lordaeronHeavyRain = FourCC("RLhr"),
  lordaronLightRain = FourCC("RLlr"),
  northrendBlizzard = FourCC("SNbs"),
  northrendHeavySnow = FourCC("SNhs"),
  northrendLightSnow = FourCC("SNls"),
  outlandHeavyWind = FourCC("WOcw"),
  outlandLightWind = FourCC("WOlw"),
  rayOfLight = FourCC("LRaa"),
  rayOfMoonlight = FourCC("LRma"),
  heavyWind = FourCC("WNcw"),
}
